{% set name = "Willow" %}
{% set version = "1.2" %}
{% set sha256 = "c4aa64db2c2a34341c4998e7d063def8384f652e9e0654eda923fd756c9f1240" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - willow

about:
  home: https://github.com/wagtail/Willow
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A unified interface to Python image libraries'
  description: |
    Willow is a simple image library that combines the APIs of Pillow, 
    Wand and OpenCV. It converts the image between the libraries when 
    necessary.
  doc_url: http://willow.readthedocs.io/en/latest/
  dev_url: https://github.com/wagtail/Willow

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
