travis:
  secure:
    BINSTAR_TOKEN: Gg9OtIZrK7lQMBKPsALIp9owkYZ4oqQOkrSnEh8dhP7VgzXQYsUyssRt2WHa8gZB6vRSgVxdiJ3I3los1fRtRZcoJ5TVDXbcZMWYK4HwjIXNynFAwWSIUML/87Ez2LR2VLqVqo6dC69JziA/e3H1V2OPVTwbhseXJkPGrO2myVL1GOZdClsePs4NHhgkex48uDsYxmsLfknpn4IAde4dPf/fvAMx98N6XnEHv4yCSgFEujXa40DHRGM8B3TSzeyEqrDAlrJVvzT5N9n0e5gaRvnWol3FVYroTjvBh26HRvHYzQrCvaXnY7GsGstxUBwLsg5tALUfR5Sew9MD9gET0IrAi1SDF1NFCvfq+YVNC6HiyO/W5ZbedKGHw2i4KNcEMQR+2SbHa9AdrrJJv7laI3VuHQzhmVORgAt9zWpztXuA+XLAr7W2xXPymZB67Q30tJOkaAwH8ICh0HVLbivQcL56qMWpYVItMqNN95cuihsS9RbpWX75ihLpcFTJdGz+5jUuNsJYGebIXziBVDLP/+jI31P6liWTn/v1e8mHqI1nBAVtUNM+XrZ65gdurqw9qJU1MfK60I2DRBvp43tBbQlcywjEUFXjpQv7GOmCoID/fLiElvJt8lYgQUlpd6bHMdyzyzblDhMLm9ZD7Ns74DUP87/1hNBXwcsUfxSuWLk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
