travis:
  secure:
    BINSTAR_TOKEN: ABtWhd9LtLYBgy7n1KMCAQAWWUFJXI1KNXh1nO+UQXodbT9HYtMDvlvyW5XFTQit04PIvq3HUTcllxCfklmArrp8bIcS7z9qyrHFSv53TL9Gk4cWQB6rOH2gC4zmdr3rKo8JFmiRxOS5p1lpHnIcVi6a1Z8gEXxXBEp03V0xosMhDZW0D9QDQyL05RW2RcAfSi/6AZVwmzCOb9emAFDsQevSYySwWVqANKudWkgAQSAgXNACzFxVb1aqT7e5mekayhbGyDPiuSwNnYN4AMm7FFDNCDbV344TTnAQzAa5cceofV5lS5iczpKK0pzwIvjVPHqQFdo1wltLpFcAcRfcq6oMoyjLNpQUZeY9zeIrM8hQgiAH4AJF0wXloA9KZNP3Rfx4r1Xv7lgAxcMTdE1tuCZ8AxISJGO/dshkqnyfQa/ryMV8SP3n2vSE+vCv/TzpMX8sg+ekX7Yn7sSClnnV5mVdAaTX0zreGYb4gfQh0qaHdH1iwpq/vqHVnSUqYc3RJBzhCzKi4xU5H1B+2KTy2pFsV75sEkz/G2FzoWkcli7JR+GFLtgibMv3+neqx3xGpi3Jdofwa3bXko0A6MnAWnvoq38juVwWpCm8mFvKX5AZvsEK/i0Os0rlt0ctDxSx7UoT8ObAuhv78O7PRNPxa/IPuCANuxhR/AJItWIBZk8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
